FROM eclipse-temurin:21-jdk
ARG MONGO_DB
ARG MONGO_HOST
ARG MONGO_PASS
ARG MONGO_PORT
ARG MONGO_USER
ARG OPENAI_APIKEY
ARG OPENAI_MODEL
#ENV MONGO_DB $MONGO_DB \
#    MONGO_HOST $MONGO_HOST \
#    MONGO_PASS $MONGO_PASS \
#    MONGO_PORT $MONGO_PORT \
#    MONGO_USER $MONGO_USER \
#    OPENAI_APIKEY $OPENAI_APIKEY \
#    OPENAI_MODEL $OPENAI_MODEL
RUN echo $MONGO_DB $MONGO_HOST $MONGO_PASS $MONGO_PORT $MONGO_USER $OPENAI_APIKEY $OPENAI_MODEL
WORKDIR /app
COPY /target/emotional-0.0.1-SNAPSHOT.jar emotional-api.jar
EXPOSE 8080
LABEL authors = "luis.bolivar"
CMD ["java", "-jar", "emotional-api.jar"]