### create a new brand
POST localhost:8080/1/brand/
Content-Type: application/json

{
  "name": "La Monjita",
  "description": "Es una empresa que se encarga de hacer bebidas tradicionales mexicanas en polvo",
  "competitors": "https://www.fake.com, https://www.fake2.com, https://www.fake3.com"
}

### get a brand by id
GET localhost:8080/1/brand/767f2e68-54b1-4976-8dc1-3abad840bd17