## compute a message.
POST localhost:8080/1/emotional/compute/
Content-Type: application/json

{
  "message": "Hoy fue un dia con mucho por hacer, logré muchas cosas y me la pase super bien, estoy contento con los resultados"
}

### get message processed by id emotional estimation.
GET localhost:8080/1/emotional/compute/4b530067-91fe-42de-8e2a-3aee0b6d56b9


### compute a list
POST localhost:8080/1/emotional/compute/batch/
Content-Type: application/json

{
  "messages": [
    "adicional: ¿Cuál es tu percepción y/o experiencia con los sustitutos de comida?",
    "No estoy seguro de qué son",
    "es buenísimo de sabor y si lo combinas con ejercicios, seguro que te funciona mucho más",
    "No sé si tiene efectividad",
    "no los sustituyo, complemento"
  ]
}

### get all message processed by batch id.
GET localhost:8080/1/emotional/compute/batch/1c41b8f4-e7cb-4f30-947a-8692f7d026e9

### create a emotional unique comput
POST localhost:8080/1/emotional/compute/unique/
Content-Type: application/json

{
  "messages": [
    "No estoy seguro de qué son",
    "es buenísimo de sabor y si lo combinas con ejercicios, seguro que te funciona mucho más",
    "No sé si tiene efectividad",
    "no los sustituyo, complemento"
  ]
}

### Get a emotional unique compute by id
GET localhost:8080/1/emotional/compute/unique/b6fbb344-da94-4433-b3f6-d67540d32ccc