name: Deploy to AWS
on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    environment: test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: 'us-east-1'
          mongo-db: ${{secrets.MONGO_DB}}
          mongo-host: ${{secrets.MONGO_HOST}}
          mongo-port: ${{secrets.MONGO_PORT}}
          mongo-user: ${{secrets.MONGO_USER}}
          openai-apikey: ${{secrets.OPENAI_APIKEY}}
          openai-model: ${{secrets.OPENAI_MODEL}}
          prompt-clean: ${{secrets.PROMPT_CLEAN}}
          prompt-emotional: ${{secrets.PROMPT_EMOTIONAL}}
          prompt-emotional-unique: ${{secrets.PROMPT_EMOTIONAL_UNIQUE}}
          prompt-keyphrase: ${{secrets.PROMPT_KEYPHRASE}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: delete, pull image
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: krate-ai
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version
          sudo chmod 666 /var/run/docker.sock
          docker rmi -f krate-ai
          docker pull $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker image tag $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG krate-ai:latest
          docker images

      - name: run krate-ai
        id: run-krate-ai
        run: |
          echo "Empezamos a correr el servicio"
          docker run -e MONGO_DB=$MONGO_DB -e MONGO_HOST=$MONGO_HOST -e MONGO_PASS=$MONGO_PASS -e MONGO_PORT=$MONGO_PORT -e MONGO_USER=$MONGO_USER -e OPENAI_APIKEY=$OPENAI_APIKEY -e OPENAI_MODEL=$OPENAI_MODEL -p 8080:8080 krate-ai:latest
