name: ci
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    environment: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: validaciones
        run: |
          java --version

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: login docker hub
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: docker built
        run: |
          docker build -t krate-ai .
          docker images

      - name: tagging image
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          docker image tag krate-ai:latest krate-ai:$IMAGE_TAG
          docker images

      - name: push image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker push $DOCKER_USER/krate-ai

      - name: validar la imagen
        id: validate-imae
        run: echo $GITHUB_OUTPUT

